menu:
- {name: 'home', url: ''}
- {name: 'research', url: '/research'}
- {name: 'teaching', url: '/teaching'}
- {name: 'blog', url: '/blog'}

social:
- {icon: 'github', link: 'https://github.com/saimamunuru'}
- {icon: 'twitter', link: 'https://twitter.com/smamunuru'}
- {icon: 'list', link: 'https://www.dropbox.com/s/dvv84kadlp59hen/Mamunuru_CV%20%285%29.pdf?dl=0'}
- {icon: 'envelope', link: 'https://www.dropbox.com/s/dvv84kadlp59hen/Mamunuru_CV%20%285%29.pdf?dl=0'}

