menu:
- {name: 'home', url: ''}
- {name: 'research', url: '/research'}
- {name: 'teaching', url: '/teaching'}
- {name: 'cv', url: '/cv'}

social:
- {icon: 'mdi:github', link: 'https://github.com/saimamunuru'}
- {icon: 'mdi:twitter', link: 'https://twitter.com/smamunuru'}
- {icon: 'mdi:email', link: 'mailto:sai@whitman.edu'}

