menu:
- {name: 'home', url: ''}
- {name: 'research', url: '/research'}
- {name: 'teaching', url: '/teaching'}

social:
- {icon: 'github', link: 'https://github.com/saimamunuru'}
- {icon: 'twitter', link: 'https://twitter.com/smamunuru'}

